apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-master-podautoscaler

spec:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-master