apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api.niwac.cn-tls
  namespace: default
spec:
  dnsNames:
    - api.niwac.cn
  secretName: api.niwac.cn-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer