apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hiwac.cn-tls
  namespace: default
spec:
  dnsNames:
    - hiwac.cn
  secretName: hiwac.cn-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer