apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: niwac.cn-tls
  namespace: default
spec:
  dnsNames:
    - niwac.cn
  secretName: niwac.cn-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer