apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www.hiwac.cn-tls
  namespace: default
spec:
  dnsNames:
    - www.hiwac.cn
  secretName: www.hiwac.cn-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer